# With these settings, devshell and pydevshell commands open a buffer
# inside your current Emacs instance.
OE_TERMINAL = "custom"
emacs_cmd = '$EMACS_BITBAKE_DEVSHELL "{title}" "{command}" "{cwd}"'
OE_TERMINAL_CUSTOMCMD := "sh -c '${emacs_cmd}'"